### ISSUE TITLE
get-started中后三个使用场景跳转链接失效

### ISSUE THREAD

**Issue by Snychng** [SynopAI/HomePage#2]
get-started中后三个使用场景跳转链接失效

不知道为啥🤷

https://github.com/SynopAI/HomePage/blob/fe2a443be3a4ea5008d6543b3e530558ee3bb87a/docs/get-started.md?plain=1#L21-L31

**Comment by Mrered** [comment]
b8dae4014820d60a9dd3ee0181b34da50e5ceabd
